\documentclass{article}

\begin{document}
\title{Exploring Variation in MEPs’ Adoption and Use of Twitter as a Representational Tool}
\author{(author)}
\maketitle
<<logit, cache=TRUE>>=
# Taken from http://www.cookbook-r.com/Statistical_analysis/Logistic_regression/
library(ggplot2)
data(mtcars)
df <- subset(mtcars, select=c(mpg,am,vs))
logr.vm <- glm(vs ~ mpg, data=df, family=binomial)
logr.vm <- glm(vs ~ mpg, data=df, family=binomial(link="logit"))
summary(logr.vm)

ggplot(df, aes(x=mpg, y=vs)) + geom_point() + 
  stat_smooth(method="glm", family="binomial", se=FALSE)


plot(df$mpg, df$vs)
curve(predict(logr.vm, data.frame(mpg=x), type="response"), add=TRUE) 
@
test
\end{document}
